#!/usr/bin/env bash

rm -rf gtfs-openov-nl.zip

wget http://gtfs.openov.nl/gtfs/gtfs-openov-nl.zip

mkdir gtfs
tar zxf gtfs-openov-nl.zip --directory gtfs

mysql  -u $1 -p"$2" < create-tables.sql

current_path=$(pwd)

feed_files=('agency' 'routes' 'shapes' 'calendar_dates' 'trips' 'stops' 'stop_times' 'transfers')

for i in "${feed_files[@]}"
do
    :
    echo $i
    cat load-data-infile.sql | sed "s|{folder}|$current_path|g" | sed "s|{table}|$i|g" | mysql
    echo
done
